# Conexión a la base de datos
spring.datasource.url=jdbc:mysql://192.168.1.4:3306/jukebox
spring.datasource.username=developer
spring.datasource.password=developer
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080

# Clave de la API de YouTube
youtube.api.key=AIzaSyDVgDRO586cMCpRqoHV-8YlwaxPfbJ7_s4